USE [master]
GO

/****** Object:  Database [Diplom]    Script Date: 17.05.2023 13:36:26 ******/
CREATE DATABASE [Diplom]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Diplom', FILENAME = N'E:\2019\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Diplom.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Diplom_log', FILENAME = N'E:\2019\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Diplom_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Diplom].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Diplom] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Diplom] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Diplom] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Diplom] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Diplom] SET ARITHABORT OFF 
GO

ALTER DATABASE [Diplom] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Diplom] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Diplom] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Diplom] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Diplom] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Diplom] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Diplom] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Diplom] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Diplom] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Diplom] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Diplom] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Diplom] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Diplom] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Diplom] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Diplom] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Diplom] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Diplom] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Diplom] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Diplom] SET  MULTI_USER 
GO

ALTER DATABASE [Diplom] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Diplom] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Diplom] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Diplom] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Diplom] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Diplom] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Diplom] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Diplom] SET  READ_WRITE 
GO

